name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    # Skip this job if running on the main repo to prevent failing CI/CD. Only run on student forks.
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}

    runs-on: ubuntu-latest
    env: # Or as an environment variable
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}
      ACADOS_INSTALL_DIR: ${{ github.workspace }}/acados
      LD_LIBRARY_PATH: ${{ github.workspace }}/acados/lib
      PYTHONPATH: ${{ github.workspace }}/acados/interfaces/acados_template/python

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0'
          environment-name: test-env
          init-shell: bash
          create-args: >
            python=3.12
            cmake
            make
            gcc
            gxx
          cache-environment: true

      - name: Clone and build acados
        run: |
          git clone https://github.com/acados/acados.git
          cd acados
          git submodule update --recursive --init
          mkdir -p build
          cd build
          cmake -DACADOS_WITH_C_INTERFACE=ON -DACADOS_WITH_QPOASES=ON ..
          make install -j4

      - name: Install Acados Interface
        run: |
          pip install -e ${{ github.workspace }}/acados/interfaces/acados_template
        shell: micromamba-shell {0}

      - name: Install Python project
        run: |
          pip install .[online_submission,test]
        shell: micromamba-shell {0}

      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}

      - name: Export with kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}